### ISSUE TITLE
Define config properties for all variants of company/game names

### ISSUE THREAD

**Issue by Rabadash8820** [DerploidEntertainment/Website#70]
Basically, define the following properties in `_config.yml` (without repetition, if possible) and use them in page text:

```yml
companyName:
  short: Derploid
  shortLegal: Derploid®
  medium: Derploid Entertainment
  mediumLegal: Derploid® Entertainment
  long: Derploid Entertainment, LLC
  longLegal: Derploid® Entertainment, LLC
highHandHoldem:
  productName: High Hand Hold'em
  productNameLegal: High Hand Hold'em™
  productNameShort: HHH
```
